Repository openshift/pod-checkpointer-operator, pull requests merged in 2018-10, with the labels that each got.

#1 add image references
  manifests/02-deployment.yaml
  manifests/image-references
Labels: approved, lgtm, size/S

#5 checkpointer: bump image to pickup required pods
  pkg/stub/handler.go
Labels: approved, lgtm, size/XS

#6 deployment: fix image path
  manifests/04-deployment.yaml
Labels: approved, size/XS

#7 docs: add README and HACKING documentation
  HACKING.md
  README.md
Labels: approved, size/M

#8 dockerfile: include binary and fix entrypoint
  Dockerfile
Labels: approved, lgtm, size/XS

#9 manifests: change startup order and tolerations for deployment.
  manifests/0000_05_pod-checkpointer-operator_01-crd.yaml
  manifests/0000_05_pod-checkpointer-operator_02-cr.yaml
  manifests/0000_05_pod-checkpointer-operator_02-rbac.yaml
  manifests/0000_05_pod-checkpointer-operator_02-service-account.yaml
  manifests/0000_05_pod-checkpointer-operator_03-role-binding.yaml
  manifests/0000_05_pod-checkpointer-operator_04-deployment.yaml
Labels: approved, lgtm, size/XS

#10 copy binary to /usr/bin
  Dockerfile
Labels: approved, lgtm, size/XS

#14 dockerfile: move binary to local bin
  Dockerfile
Labels: approved, lgtm, size/XS

#15 remove from release image
  Dockerfile
Labels: approved, lgtm, size/XS
